language: haxe

haxe:
  - 3.4.7
  - development

install:
  - haxelib git hxparse https://github.com/Simn/hxparse --never
  - haxelib git haxeparser https://github.com/Simn/haxeparser --never
  - haxelib git tokentree https://github.com/HaxeCheckstyle/tokentree --never
  - haxelib git hxargs https://github.com/Simn/hxargs --never
  - haxelib install json2object

script:
  - haxe build.hxml
