language: haxe

haxe:
  - 3.4.7
  - development

matrix:
  allow_failures:
    - haxe: 3.4.7

install:
  - haxelib git hxparse https://github.com/Simn/hxparse --never
  - haxelib git haxeparser https://github.com/Simn/haxeparser --never
  - haxelib git tokentree https://github.com/HaxeCheckstyle/tokentree --never
  - haxelib git hxargs https://github.com/Simn/hxargs --never
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs --never
  - haxelib install json2object

script:
  - haxe buildAll.hxml
  - node run.js -s . --check
  - neko run.n -s . --check
